/** @deprecated Import shader/pipeline types from `@configurator/types` instead. */
export type {
  composeLogoStampAtlasInputType,
  composeNameMaskAtlasInputType,
  drawNameMaskGeometryInputType,
  drawNameStrokeMaskGeometryInputType,
  garmentLogoStampStateType,
  garmentNameMaskStateType,
  garmentPrintStateType,
  gizmoFrameStateType,
  imageTextureOptionsType,
  logoSlotBounds4Type,
  logoSlotFloat4Type,
  logoSlotUniformsType,
  logoSlotVec2Type,
  logoStampAtlasType,
  logoStyleUniformsType,
  nameMaskAtlasType,
  nameSlotBounds4Type,
  nameSlotColor4Type,
  nameSlotFloat4Type,
  nameSlotVec2Type,
  nameStyleUniformsType,
  patternColorPairType,
  patternMaskPairType,
  pbrMapsType,
  productAppearanceTexturesType,
  stampPixelSizeType,
  textCanvasDrawOptionsType,
} from '@configurator/types';
