export { DEFAULT_CURRENCY_CODE, DEFAULT_MODEL_ID, deriveLocalBusiness, getModel, hasModel, MODELS, resolveProductPreviewSrc } from './garmentCatalog';
export { cn } from './cn';
export { canvasToPngBlobUrl } from './logoFile/canvasToBlobUrl';
export { resolveDesignThumbSrc } from './resolveDesignThumbSrc/resolveDesignThumbSrc';
export {
  normalizeDesignId,
  parseDesignIdFromPatternName,
  resolveDesignCardPreviewSrc,
  resolvePatternDesignId,
} from './resolveDesignCardPreviewSrc';
export { applyDesignSvgLayerColors, designSvgTextToDataUrl } from './applyDesignSvgLayerColors';
export { loadDesignSvgText } from './loadDesignSvgText';
export { resolveProductFlipCardSrc } from './resolveProductFlipCardSrc/resolveProductFlipCardSrc';
export type { productFlipCardSideType } from './resolveProductFlipCardSrc/resolveProductFlipCardSrc';
export { resolveProductCatalogPreviewSrc } from './resolveProductCatalogPreviewSrc/resolveProductCatalogPreviewSrc';
export {
  getCatalogProductEntry,
  getCatalogProductEntryBySlug,
  listCatalogProducts,
  listCatalogProductsByCollection,
  listOtherProductCollections,
  resolveCartItemDisplayPreview,
  resolveCartItemPreviewSrc,
  resolveConfiguratorProductBySlug,
  toCatalogProductRef,
} from './productCatalog';
export { getCheckoutDeliveryTimeline } from './checkoutDeliveryDates';
export { CHECKOUT_SUMMARY_ICON_MAP } from './checkoutSummaryIcons';
export { priceFormat } from './priceFormat';
export { isAcceptedLogoFile, LogoFileError, logoFileToDisplayUrl, preloadLogoDisplayUrl, warmupGhostscriptWorker, yieldToMain } from './logoFile';
export { withListPunctuation } from './modalInfo';

/** @deprecated Import from `@configurator/utils` instead. */
export {
  GARMENT_SHADER_VERSION,
  ORBIT_SURFACE_CLEARANCE,
  applyGarmentGizmoButtonsReveal,
  applyGarmentGizmoFrame,
  applyGarmentGizmoHover,
  applyGarmentGizmoIcons,
  applyGarmentGizmoRotation,
  applyGarmentGradient,
  applyGarmentLogoGizmoButtonsReveal,
  applyGarmentLogoGizmoFrame,
  applyGarmentLogoStamp,
  applyGarmentLogoStyle,
  applyGarmentNameMasks,
  applyGarmentNameStyle,
  applyGarmentNumberGizmoButtonsReveal,
  applyGarmentNumberGizmoFrame,
  applyGarmentNumberMasks,
  applyGarmentNumberStyle,
  applyGarmentPartUvBounds,
  applyGarmentPatternTints,
  applyGarmentPrint,
  applyGarmentPrintAtlasSize,
  applyGarmentTestoGizmoButtonsReveal,
  applyGarmentTestoGizmoFrame,
  applyGarmentTestoMasks,
  applyGarmentTestoStyle,
  applyOrbitZoomAroundPoint,
  buildGizmoFrameUniforms,
  buildLineHeightStyleUniforms,
  buildLogoGizmoFrameUniforms,
  buildLogoStyleUniforms,
  buildNameStyleUniforms,
  buildNumberStyleUniforms,
  buildTestoStyleUniforms,
  captureConfiguratorPreview,
  captureConfiguratorPreviewSnapshot,
  clampOrbitCameraOutsideGarment,
  clampOrbitTargetToGarment,
  clampUvToPartBounds,
  clearImageTextureCache,
  composeLogoPrintAtlas,
  composeLogoStampAtlas,
  composeNameMaskAtlas,
  configureImageTextureSampling,
  configureMaskTextureSampling,
  createGarmentMaterial,
  DEFAULT_LINE_HEIGHT,
  drawNameMaskGeometry,
  drawNameStrokeMaskGeometry,
  emptyMaskPair,
  getEmptyPrintTexture,
  getProductAppearanceTextures,
  hasPrintableGarmentParts,
  hydrateGarmentLogoUniforms,
  hydrateGarmentNameUniforms,
  hydrateGarmentNumberUniforms,
  hydrateGarmentTestoUniforms,
  imageToMaskTexture,
  imageToTexture,
  isColorOnlyGarmentPart,
  isOrbitControlsEnabled,
  isUvInsidePartBounds,
  loadCachedImage,
  loadImage,
  measureNameGizmoHalf,
  measureNameStampPixelSize,
  orbitControlsRef,
  packPatternMaskChannels,
  packStackedTextMaskCanvas,
  packStackedTextMaskTexture,
  canvasToMaskTexture,
  canvasToTexture,
  preloadGarmentAppearance,
  preloadGarmentProduct,
  preloadGarmentProductAssets,
  readProductAppearanceTextures,
  recenterOrbitTargetByZoom,
  registerAsideOrbitGuard,
  registerConfiguratorPreviewCapture,
  repairPrintInstancePlacement,
  resolveCursorFocusPoint,
  resolveGarmentCenter,
  resolveGizmoContentRotationDeg,
  resolveGizmoElementRotationDeg,
  resolveLogoDisplayScale,
  resolveLogoDrawSize,
  resolveLogoGizmoHalf,
  resolveLogoReferenceDrawSize,
  resolveModelUrl,
  resolveNameStampSize,
  resolvePartPrintRotation,
  resolvePartTextureSize,
  resolvePartUvBounds,
  resolvePrintAtlasSize,
  resolvePrintLocalUvToAtlas,
  resolveProductGizmoRotation,
  resolveRasterDesignSrc,
  resolveRotatedGizmoHalf,
  resolveTextContentRotationDeg,
  resolveTextGizmoHalf,
  resolveTextGizmoMeasureOptions,
  scheduleGarmentShaderUpgrade,
  setAsidePointerOver,
  setGizmoDragging,
  suppressThreeClockDeprecation,
  syncProductAppearanceTextures,
  unionStampPixelSize,
  unregisterConfiguratorPreviewCapture,
  upgradeGarmentMaterialShader,
} from '@configurator/utils';
